### ISSUE TITLE
Pad BRB History amount item with two zeros

### ISSUE THREAD

**Issue by whoiswillma** [cuappdev/eatery-backend#120]
Currently the iOS frontend receives the history amount as a string. Although it is a worthwhile discussion to have as to whether to change the history amount to a numeric value, for now the backend should pad the amount string with two 0's. 

![IMG_1786](https://user-images.githubusercontent.com/1882991/64293934-a8970380-cf3b-11e9-945a-d91d887321c0.jpg)

**Comment by orkosinha** [comment]
Fixed in #123
